package com.opopz.mgmt.data.domain;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * CoBlock generated by hbm2java
 */
@Entity
@Table(name = "co_block", catalog = "co")
public class CoBlock implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private Integer time;
	// private Integer user;
	private Integer wid;
	private Integer x;
	private Integer y;
	private Integer z;
	private Integer type;
	private Integer data;
	private byte[] meta;
	private Integer action;
	private Boolean rolledBack;


	private CoUser user;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="user")
	public CoUser getUser()
	{
		return this.user;
	}

	public void setUser(CoUser user)
	{
		this.user = user;
	}
	
	
	
	
	public CoBlock()
	{
	}

	public CoBlock(Integer time, CoUser user, Integer wid, Integer x, Integer y, Integer z, Integer type, Integer data,
			byte[] meta, Integer action, Boolean rolledBack)
	{
		this.time = time;
		this.user = user;
		this.wid = wid;
		this.x = x;
		this.y = y;
		this.z = z;
		this.type = type;
		this.data = data;
		this.meta = meta;
		this.action = action;
		this.rolledBack = rolledBack;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}

	@Column(name = "time")
	public Integer getTime()
	{
		return this.time;
	}

	public void setTime(Integer time)
	{
		this.time = time;
	}

//	@Column(name = "user")
//	public Integer getUser()
//	{
//		return this.user;
//	}
//
//	public void setUser(Integer user)
//	{
//		this.user = user;
//	}

	@Column(name = "wid")
	public Integer getWid()
	{
		return this.wid;
	}

	public void setWid(Integer wid)
	{
		this.wid = wid;
	}

	@Column(name = "x")
	public Integer getX()
	{
		return this.x;
	}

	public void setX(Integer x)
	{
		this.x = x;
	}

	@Column(name = "y")
	public Integer getY()
	{
		return this.y;
	}

	public void setY(Integer y)
	{
		this.y = y;
	}

	@Column(name = "z")
	public Integer getZ()
	{
		return this.z;
	}

	public void setZ(Integer z)
	{
		this.z = z;
	}

	@Column(name = "type")
	public Integer getType()
	{
		return this.type;
	}

	public void setType(Integer type)
	{
		this.type = type;
	}

	@Column(name = "data")
	public Integer getData()
	{
		return this.data;
	}

	public void setData(Integer data)
	{
		this.data = data;
	}

	@Column(name = "meta")
	public byte[] getMeta()
	{
		return this.meta;
	}

	public void setMeta(byte[] meta)
	{
		this.meta = meta;
	}

	@Column(name = "action")
	public Integer getAction()
	{
		return this.action;
	}

	public void setAction(Integer action)
	{
		this.action = action;
	}

	@Column(name = "rolled_back")
	public Boolean getRolledBack()
	{
		return this.rolledBack;
	}

	public void setRolledBack(Boolean rolledBack)
	{
		this.rolledBack = rolledBack;
	}

}
