package com.opopz.mgmt.data.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CoEntity generated by hbm2java
 */
@Entity
@Table(name = "co_entity", catalog = "co")
public class CoEntity implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private Integer time;
	private byte[] data;

	public CoEntity()
	{
	}

	public CoEntity(Integer time, byte[] data)
	{
		this.time = time;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}

	@Column(name = "time")
	public Integer getTime()
	{
		return this.time;
	}

	public void setTime(Integer time)
	{
		this.time = time;
	}

	@Column(name = "data")
	public byte[] getData()
	{
		return this.data;
	}

	public void setData(byte[] data)
	{
		this.data = data;
	}

}
