package com.opopz.mgmt.data.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CoSign generated by hbm2java
 */
@Entity
@Table(name = "co_sign", catalog = "co")
public class CoSign implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private Integer time;
	private Integer user;
	private Integer wid;
	private Integer x;
	private Integer y;
	private Integer z;
	private String line1;
	private String line2;
	private String line3;
	private String line4;

	public CoSign()
	{
	}

	public CoSign(Integer time, Integer user, Integer wid, Integer x, Integer y, Integer z, String line1, String line2,
			String line3, String line4)
	{
		this.time = time;
		this.user = user;
		this.wid = wid;
		this.x = x;
		this.y = y;
		this.z = z;
		this.line1 = line1;
		this.line2 = line2;
		this.line3 = line3;
		this.line4 = line4;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}

	@Column(name = "time")
	public Integer getTime()
	{
		return this.time;
	}

	public void setTime(Integer time)
	{
		this.time = time;
	}

	@Column(name = "user")
	public Integer getUser()
	{
		return this.user;
	}

	public void setUser(Integer user)
	{
		this.user = user;
	}

	@Column(name = "wid")
	public Integer getWid()
	{
		return this.wid;
	}

	public void setWid(Integer wid)
	{
		this.wid = wid;
	}

	@Column(name = "x")
	public Integer getX()
	{
		return this.x;
	}

	public void setX(Integer x)
	{
		this.x = x;
	}

	@Column(name = "y")
	public Integer getY()
	{
		return this.y;
	}

	public void setY(Integer y)
	{
		this.y = y;
	}

	@Column(name = "z")
	public Integer getZ()
	{
		return this.z;
	}

	public void setZ(Integer z)
	{
		this.z = z;
	}

	@Column(name = "line_1", length = 100)
	public String getLine1()
	{
		return this.line1;
	}

	public void setLine1(String line1)
	{
		this.line1 = line1;
	}

	@Column(name = "line_2", length = 100)
	public String getLine2()
	{
		return this.line2;
	}

	public void setLine2(String line2)
	{
		this.line2 = line2;
	}

	@Column(name = "line_3", length = 100)
	public String getLine3()
	{
		return this.line3;
	}

	public void setLine3(String line3)
	{
		this.line3 = line3;
	}

	@Column(name = "line_4", length = 100)
	public String getLine4()
	{
		return this.line4;
	}

	public void setLine4(String line4)
	{
		this.line4 = line4;
	}

}
