package com.nikemc.mgmt.data.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CoMaterialMap generated by hbm2java
 */
@Entity
@Table(name = "co_material_map", catalog = "co")
public class CoMaterialMap implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private Integer id;
	private String material;

	public CoMaterialMap()
	{
	}

	public CoMaterialMap(Integer id, String material)
	{
		this.id = id;
		this.material = material;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}

	@Column(name = "id")
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "material")
	public String getMaterial()
	{
		return this.material;
	}

	public void setMaterial(String material)
	{
		this.material = material;
	}

}
