package com.nikemc.mgmt.data.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoSession generated by hbm2java
 */
@Entity
@Table(name = "co_session", catalog = "co")
public class CoSession implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private Integer time;
	//private Integer user;
	private Integer wid;
	private Integer x;
	private Integer y;
	private Integer z;
	private Integer action;


	private CoUser user;
	
	@ManyToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="user")
	public CoUser getUser()
	{
		return this.user;
	}

	public void setUser(CoUser user)
	{
		this.user = user;
	}
	
	
	
	public CoSession()
	{
	}

	public CoSession(Integer time, CoUser user, Integer wid, Integer x, Integer y, Integer z, Integer action)
	{
		this.time = time;
		this.user = user;
		this.wid = wid;
		this.x = x;
		this.y = y;
		this.z = z;
		this.action = action;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}

	@Column(name = "time")
	public Integer getTime()
	{
		return this.time;
	}

	public void setTime(Integer time)
	{
		this.time = time;
	}

//	@Column(name = "user")
//	public Integer getUser()
//	{
//		return this.user;
//	}
//
//	public void setUser(Integer user)
//	{
//		this.user = user;
//	}

	@Column(name = "wid")
	public Integer getWid()
	{
		return this.wid;
	}

	public void setWid(Integer wid)
	{
		this.wid = wid;
	}

	@Column(name = "x")
	public Integer getX()
	{
		return this.x;
	}

	public void setX(Integer x)
	{
		this.x = x;
	}

	@Column(name = "y")
	public Integer getY()
	{
		return this.y;
	}

	public void setY(Integer y)
	{
		this.y = y;
	}

	@Column(name = "z")
	public Integer getZ()
	{
		return this.z;
	}

	public void setZ(Integer z)
	{
		this.z = z;
	}

	@Column(name = "action")
	public Integer getAction()
	{
		return this.action;
	}

	public void setAction(Integer action)
	{
		this.action = action;
	}

}
