package com.nikemc.mgmt.data.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * CoVersion generated by hbm2java
 */
@Entity
@Table(name = "co_version", catalog = "co")
public class CoVersion implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rowid;
	private String version;
	private Integer time;

	public CoVersion()
	{
	}

	public CoVersion(Integer time)
	{
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rowid", unique = true, nullable = false)
	public Integer getRowid()
	{
		return this.rowid;
	}

	public void setRowid(Integer rowid)
	{
		this.rowid = rowid;
	}
	
	@Column(name = "version", length = 16)
	public String getVersion()
	{
		return this.version;
	}

	public void setVersion(String version)
	{
		this.version = version;
	}

	@Column(name = "time")
	public Integer getTime()
	{
		return this.time;
	}

	public void setTime(Integer time)
	{
		this.time = time;
	}

}
